### ISSUE TITLE
Center map on user

### ISSUE THREAD

**Issue by missinglink** [pelias/leaflet-plugin#107]
Currently the map in the demo defaults the user to New York rather than their own location.

This effects the search bias and so when users view the demo from overseas the results will strongly bias towards NYC, which is perceived as unintuitive and confusing (something the API tries hard to avoid).

So presumably 3rd party integrations will need to trigger the browser device location API themselves? is this currently part of this library? should it be part of this library? can we prompt for the location privilege in the demo so the map centers on the user?

If the device location popup is an issue I can hook up a quick'n'dirty geoip API to use instead. Eg. https://bits.wikimedia.org/geoiplookup

Thoughts?

**Comment by louh** [comment]
I'd keep any device location API access out of the library -- there are plenty of other Leaflet plugins that will handle it, anyway.

I didn't know there was a publicly / freely accessible geo IP service out there. I think it would be great to hook the demo up to use that. I've been cautious about requesting for user's location unless these conditions are true: (a) the page uses that information ASAP after a user approves it (in this case, yes) (b) the user expects that page to know their location in order to be useful immediately (e.g. weather and travel apps; but for generic search demos, not necessarily). So my primary critique is that if we have to ask for permission first, we block loading for reasons that aren't apparent for the user. I really like the Geo IP lookup though.

**Comment by louh** [comment]
I just added the GeoIP lookup to the demo page. This should be working if the geoIP API is not blocked (NYC is the fallback). http://mapzen.github.io/leaflet-geocoder/

What do you think?

**Comment by riordan** [comment]
💯

**Comment by missinglink** [comment]
wunderbar!

**Comment by louh** [comment]
Cool, closing now
