### ISSUE TITLE
Rename/clarify terminology

### ISSUE THREAD

**Issue by riordan** [pelias/leaflet-plugin#12]
Lots of colloquial terms
- `drop pin`
  -`pan to point`
- `full_width`
- `expanded`
- `hide_other_controls`

How might we make these (and other) terms clearer?

**Comment by louh** [comment]
I changed some of these in v1
- `dropPin` is changed to `markers` - for no reason other than to match the terminology Leaflet uses.
- `hide_other_controls` is removed. The more I think about it, the more I think this isn't the purview of the library to force that particular UX opinion on users, especially since it's a blunt force solution: we don't know exactly what we're hiding, only that other controls (from Leaflet or other libraries) might exist and they should all go away, dammit. I think what we ought to do is recognize that whoever is responsible for integrating the plugin needs to make their own decisions (and write their own code) about what controls are visible and what's not, and when to do it.

Options still using the same terminology:
- `full_width` is renamed `fullWidth` to correspond with Leaflet standards on using camelCase names, but the words are still the same
- `expanded` is unchanged so far
