### ISSUE TITLE
Autocomplete does not throttle

### ISSUE THREAD

**Issue by brunobg** [pelias/leaflet-plugin#130]
Autocomplete seems to be throttled in the code, but it doesn't work. Requests are sent immediately, no throttling happens. Is it supposed to work and wait 250ms before making a request or is the throttle() function for something else? Very easy to reproduce, happens in every browser.

**Comment by louh** [comment]
Hi @brunobg,

Are you getting `429 "Too Many Requests"` error codes in response?

A single request is definitely sent immediately. The throttle prevents _subsequent_ requests from happening too quickly in succession. Suppose you typed "s", you would immediately send a request for autocomplete results beginning with the letter "s". If you then typed "seat", but typing "ea" happened in less than 250ms, then the plugin does not send another request until after typing the "t". Therefore the throttle "drops" some requests that would otherwise occur in a short time frame because they would occur too quickly and hit the [rate limits](https://mapzen.com/documentation/search/api-keys-rate-limits/) present in Mapzen Search. Does this make sense?

If throttling was completely broken, you would start seeing a `429` error code response for those requests. If this is happening, please write back and we'll try to troubleshoot this.

**Comment by brunobg** [comment]
Hi @louh. I expected the counter to reset whenever there was a keypress, instead of just throttling requests to no more than one every 250ms. This may provide partial results but was just doing 4 or 5 requests per user. I don't recall perfectly now, but I think the requests may not have been aborted too (might be my memory playing tricks). Or it showed stale results when you typed backspace. 

We ended up writing some code above yours to alter this behavior and only make requests when there was a pause of 250ms. To me this is closed, if you need some more information let me know. Thanks!

**Comment by louh** [comment]
Thanks, @brunobg. We don't abort stale requests, but we check timestamps from the response so we shouldn't be rendering any stale results. (If we are, that's a different bug, so let me know if you do encounter this.)

We're not planning to change our throttling behavior, but thank you for writing back and explaining your use case. I'll close this issue now.
