### ISSUE TITLE
Access to Marker Object(s)

### ISSUE THREAD

**Issue by mepa1363** [pelias/leaflet-plugin#132]
I would like to know if there is a way (besides hacking the code) to get access to the marker object(s). What I'm looking for is to disable popup (or change its content), and to make the marker draggable.
Thanks.

**Comment by louh** [comment]
Hi @mepa1363,

The first thing you can do (and is officially supported) is to set your default marker options during in plugin initalization:

``` js
var geocoder = L.control.geocoder('<your-api-key>', {
    markers: {
        draggable: true
    }
}).addTo(map);
```

Notice that I assigned the geocoder to a variable. This way I have access to it later, and read the `markers` property on the `geocoder` object:

``` js
console.log(geocoder.markers); // --> [ Array ]
geocoder.markers[0].setPopupContent('Hello world');
```

The array represents any markers that are currently visible, so if something in the plugin clears the markers on the map, then the references to that marker are cleaned up as well.

Referring to the markers in this way is not documented but I think it's useful if it were officially supported, so please give it a try and let me know what you think. If we can iron out any kinks in this implementation then I'll go ahead and release it as a documented feature in a future version.

**Comment by mepa1363** [comment]
Hi @louh,

Thanks for your help. Everything worked well except for the function that unbinds (disable) the popup. Is there any way to disable popups?

One more thing; I am using two geocoder controls in a single interface. Since the markers are draggable, I am sending the coordinates to the Mapzen reverse geocoder to get the address back. Now I want to change the text in the associated search box accordingly. Is there a built-in function to that? 

Thanks.

**Comment by louh** [comment]
Re: disabling popups. Hmm. It might be hard because the plugin binds and shows the popup immediately so there's not a way to hook into that and modify the behavior (without hacks). I did write a proposal for a popup option that would allow you to control its behavior, here: https://github.com/mapzen/leaflet-geocoder/issues/72, which we would need to build into the plugin. Let me know if that would work the way you'd expect.

Re: changing text in the search box after a reverse geocode - it sounds like you've implemented your own reverse geocoding functionality that occurs on marker dragging. You can set the input in the text box like this:

``` js
geocoder._input.value = 'Your text';
```

(Assuming you have `geocoder` variable assigned to one instance of the control)

`_input` is an internal variable and it's not documented, but it is not likely to change.

**Comment by mepa1363** [comment]
Hi @louh,

Thanks so much for you help. It works like a charm.
