### ISSUE TITLE
Preset location in geocoder

### ISSUE THREAD

**Issue by frankbroniewski** [pelias/leaflet-plugin#144]
Hi,
maybe it is just me not looking properly, but is there a way to preset a location in a geocoder search field? I'd like to offer routing to an known location, so setting the goal with a predefined location would be helpful. Any ideas on how I can accomplish that?
The Leaflet Routing Machine search boxes has that capability, having it on the geocoder would be great!
Frank

**Comment by missinglink** [comment]
I had a think about this, I agree it would be cleaner to implement this in the front-end rather in the search service itself.

The mapzen search api has 3 endpoints `/v1/search`, `/v1/autocomplete` & `/v1/reverse`.

I think it would be better to have the frontend detect if the input text is a coordinate pair and use the `/v1/reverse` API instead of one of the other two.

The other option would be to implement this feature in https://github.com/pelias/api, but doing so would return documents from the `/v1/search` endpoint that were in the response format of `/v1/reverse`, which would be weird and potentially lead to bugs.

@frankbroniewski would the input be `lon, lat` or `lat, lon`, would you also expect a format such as `52°52 N 13°37 E` to work?

@louh is this something you would be interested in including in the API?

**Comment by louh** [comment]
Let me know if I'm reading this wrong, but it sounds like @frankbroniewski just wants to pre-populate the input box with some text? I don't think this needs to touch the Mapzen Search API at all.

**Comment by frankbroniewski** [comment]
No, presetting a text would be easy. I am looking for a solution to initialize a geocoder with a predefined location, either by name or by coordinates.
I have two geocoder in my map, one for the from-location and one for the destination-location. The destination should be preset in order to give the user a suitable location, but changeable if desired.
I hope that makes it a bit more clear.

**Comment by louh** [comment]
Is this saying that the geocoder already "found" a location? When you say predefined location, you mean that the geocoder behaves as if a search was already performed, so it "knows" not just the input but also the lat/lng point for that location?

**Comment by frankbroniewski** [comment]
Sorry for the late reply, but you describe my wish very well

**Comment by louh** [comment]
I must also apologize for the super late reply, but I am currently working through the back log of issues here. It sounds like you might be able to achieve this if you save a GeoJSON feature containing your pre-set location, then call this method on the geocoder after instantiating it:

```js
var myPresetLocation = require('./preset.json'); // Assumes a browserify context
var myPresetLocationInput = 'my preset input'

geocoder.showResults(myPresetLocation, myPresetLocationInput);
geocoder._input.value = myPresetLocationInput;
```

This is not using documented functionality so I cannot guarantee that it will work for eternity but I hope gets you close to what you are looking for.
