### ISSUE TITLE
npm import leading to missing styles?

### ISSUE THREAD

**Issue by jakehm** [pelias/leaflet-plugin#148]
The searchbox looks strange and I think the issue is that the css is not loading.

I am using this with react-leaflet.

```
import { MapControl } from 'react-leaflet'
import L from 'leaflet'
import 'leaflet-geocoder-mapzen'

export default class SearchBox extends MapControl {

  componentWillMount () {
    const options = {
      focus: true,
      position: 'topright',
      attribution: null
    }
    const searchBox = L.control.geocoder('mapzen-mNEwdS8', options)
    this.leafletElement = searchBox
  }
}

```

And what I get looks like this:
![image](https://cloud.githubusercontent.com/assets/8211311/20732148/527b7dc4-b65b-11e6-9931-972d8925ef89.png)

**Comment by louh** [comment]
Hi @jakehm,

CSS won't be loaded automatically. Are you including it in your page, e.g. a direct link to the CSS stylesheet, like so:

https://github.com/mapzen/leaflet-geocoder/blob/master/index.html#L12

or otherwise importing the `dist/leaflet-geocoder-mapzen.css` file?

Another possible culprit is the version you are using. Version 1.7.0 was published incorrectly without CSS files, but 1.7.1 should include them.
