### ISSUE TITLE
Discrepancies between search & autocomplete results

### ISSUE THREAD

**Issue by dway8** [pelias/leaflet-plugin#164]
Hello,

I am encountering a problem on your demo page. When I input "14 rue Fernand Rey", no results are found. But when I press "Enter",  the right address is shown in the results (14 rue Fernand Rey, Lyon, France).

Why is it displayed with the "search" endpoint, and not with the "autocomplete" endpoint?

Thanks!

**Comment by dianashk** [comment]
Hi @dway8, thanks for reaching out. 
Autocomplete and search endpoints behave differently at this time because only search supports address Interpolation. Interpolation is the process of estimating house numbers where an exact match is not found in the data. We are working on adding this functionality to autocomplete as well but it will still be another months or so before that makes it to production.
