### ISSUE TITLE
Using leaflet-geocoder with Glitch

### ISSUE THREAD

**Issue by dphiffer** [pelias/leaflet-plugin#169]
I've been tinkering with [maps on Glitch](https://glitch.com/edit/#!/smol-maps) and encountered the following situation:

* Added `leaflet-geocoder-mapzen` to my [bower.json](https://github.com/smoldata/smol-maps/blob/master/bower.json) file
* In my [Makefile](https://github.com/smoldata/smol-maps/blob/master/Makefile) I have these steps to build `dist` JS and CSS:  
    ```
    cd public/lib/leaflet-geocoder-mapzen && npm install
    cd public/lib/leaflet-geocoder-mapzen && npm run-script build
    ```
* When I try running this on Glitch, it causes the instance to run out of space because PhantomJS is a beast.  
    ```
    Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1511279685744/phantomjs-2.1.1-linux-x86_64 -> /app/public/lib/leaflet-geocoder-mapzen/node_modules/phantomjs-prebuilt/lib/phantom
    Writing location.js file
    Phantom installation failed { Error: ENOSPC: no space left on device, write
        at Object.fs.writeSync (fs.js:735:20)
    ```

I see two ways of addressing this, and I'd be curious to get input before I try doing anything:
1. Include pre-built `dist` JS and CSS so that individual users don't need to `npm install`
2. Remove PhantomJS from the packages that get installed with `npm install`

Thanks!

**Comment by dphiffer** [comment]
Of course a 3rd route is for me to just bundle my own copies of the `dist` assets in my own repo, but this seems less ideal since it means that I stop getting the benefits of package managers keeping things up to date.

**Comment by dphiffer** [comment]
I guess my inclination here is to go with option 1: add an additional step to the [Versioning and Publishing](https://github.com/mapzen/leaflet-geocoder/blob/master/CONTRIBUTING.md#versioning-and-publishing) process to build `dist` assets and commit them.

**Comment by dphiffer** [comment]
One other detail that's important: my map project is intended to be offline-friendly, so using the CDN-hosted version is less good for me. I am trying to support offline-ness and Glitch, which is maybe a weird combo.

**Comment by louh** [comment]
Generally speaking, most package authors won't include `dist` assets inside of a repository. One of the reasons for this is because compiled assets are often a source of merge conflicts and can make history really messy. I have seen packages include `dist` assets for historical reasons (or for very good reasons) but it seems like you're looking for more of a workaround.

I'll throw a couple of other options into the mix:

1. Since your `npm install` step requires online access anyway, you could have your Makefile make a local copy of the CDN assets instead. The CDN assets should be _just as_ supported since it is the canonical way of using the assets directly for people who do not have build steps.

2. If you want to make a structural change to this repository, you could move PhantomJS to `peerDependencies`. This means `npm install` would skip installing PhantomJS, but any environment that needs to run tests, like Circle, would need its own install step for PhamtomJS, and you could update the development instructions to make that clear. (This won't necessarily solve this if other dependencies are installing PhantomJS on its own, though -- run `npm list` to make sure.)

**Comment by dphiffer** [comment]
Yeah that makes sense, I'll go the download-from-a-CDN route for now. Thanks @louh!
