### ISSUE TITLE
Mapzen closing down

### ISSUE THREAD

**Issue by mubashirqasim** [pelias/leaflet-plugin#174]
Hi there,

This was really handy geo-coder package.
You might have heard that Mapzen is closing down and as a result their geo-coder is not work anymore.
Do you have a plan to upgrade it with any working geo-coder?

![capture](https://user-images.githubusercontent.com/8086373/37805752-062af566-2ea1-11e8-8809-c8e0a5a75df8.PNG)

**Comment by missinglink** [comment]
Hi @mubashirqasim, you can request an API key from https://geocode.earth

You'll just need to use your new API key and the following options when loading the plugin:
```
  url: 'https://api.geocode.earth/v1',
  attribution: 'Geocoding by <a href="https://geocode.earth/">geocode.earth</a>'
```

**Comment by mubashirqasim** [comment]
Thanks for your prompt response Peter. https://geocode.earth service is quite expensive though.

**Comment by missinglink** [comment]
The geocode.earth plans are geared towards businesses, it ends up costing a fair bit to have a production system running at that scale.

Unfortunately since the shutdown of mapzen there is no free hosted pelias service available and no-one has come forward and offered to foot the bill for one :(

You'll always have the option of running your own server, all the code is open source and all the data is also open.

You can open an issue on the pelias repo directly for more info on how to do that.

**Comment by missinglink** [comment]
Contact Julian via the geocode.earth site and tell him what you plan to do, he'll give you a demo key to try it out for free and you might be able to figure out something that works.

**Comment by gopi-ar** [comment]
We've hosted a pelias instance at LocationIQ.org for Mapzen users. 10k requests / day & all the usual bells & whistles. Endpoint is: `https://pelias.locationiq.org/v1`

**Comment by missinglink** [comment]
Hi @gopi-ar I'm getting a `403 Forbidden nginx/1.12.1` message from the link you provided.

The Pelias core team is currently working on some options to form a foundation for the project which will bring together organizations interested in continuing development work on the codebase.

Since the shutdown of Mapzen the dev work has stalled, @orangejulius & I are working hard to get everything back on track since some of the services we depend on have also gone away.

Once we get a foundation set up we'd be happy if `locationiq` would participate in discussions and potentially help with funding.

Happy geocoding!

**Comment by gopi-ar** [comment]
@missinglink That's the base endpoint URL, you'll have to use /autocomplete, etc to get to the Pelias API. Tokens can be generated by signing-up at `https://locationiq.org`. Do let us know as and when the foundation is ready, we're happy to help as much as we can.

**Comment by louh** [comment]
@gopi-ar The LocationIQ endpoint does not have CORS headers provided, which makes the endpoint useless as a front-end geocoding provider -- and that's absolutely necessary for a Leaflet plugin. Do you have any plans to provide CORS headers?
