### ISSUE TITLE
Feature Request: zoom on select result

### ISSUE THREAD

**Issue by royhobbstn** [pelias/leaflet-plugin#62]
An option - integer - corresponding to Leaflets zoom levels.  Allows user to set a default zoom level when selecting a geocoding result.

Use Case: When a user is zoomed out to the state level, but searches for a small town within the state.  (In this case, simply panning to the result does not bring the user to a useful map extent).

**Comment by dianashk** [comment]
@royhobbstn, thanks for the feature request. We'll discuss this in our next planning meeting and update the issue accordingly.

The zoom issue has been a concern for us as well, and we're hoping to address it to some extent with the introduction of bounding boxes for places that have geometry. That way, we'll be able to zoom to the right level when a bounding box is present and when it's just a point, use a default zoom level that you're requesting. Do you think that would address your concern? This bounding box feature should be coming online in the next 2-3 months.

**Comment by royhobbstn** [comment]
That's an even better solution than I had in mind.  I'm looking forward to seeing that implemented.  For now I've made a quick hack for zooming that works, so no hurry.

**Comment by riordan** [comment]
Yes! We totally want this too!

We've considered this idea of setting default zooms for the different types of results (e.g. one for venues/addresses, another for cities, another for countries), but think we've got something even better coming soon.

We're looking to capture the geographic boundary of everything we import, so each place will have a bounding box that describes its size appropriately (outlined here: pelias/quattroshapes#29). It's part of our next big push, and it'll mean that if you search for a huge city or country, you'll still be able to see everything, rather than defaulting to a particular zoom size that may or may not correctly encompass the result.

**Comment by riordan** [comment]
And it appears @dianashk and I are of the same mind.

**Comment by dianashk** [comment]
@royhobbstn :+1: Glad you've been able to make it work for now. Stay tuned for improvements.

In the meantime, we'd love to learn more about how you're using the plugin and maybe even spotlight your work if you're interested in sharing it at some point. Understanding how the community is engaging with the tools is tremendously helpful in assigning priorities to tasks and adding/changing/removing functionality.

@riordan, wouldn't be the first time! :smile:

**Comment by royhobbstn** [comment]
@dianashk I learned about this project at jsgeo.  I have a few thoughts about the plugin/geocoder and I'll send you an email later today.

**Comment by dianashk** [comment]
@royhobbstn, great news! We now have a bbox property for each feature in the results. This should help you zoom out to the right level. Let us know if there are any issues with this property. The zoom level isn't updated automatically in leaflet, just yet.

**Comment by skorasaurus** [comment]
I implemented this [using an event, here's an example](https://github.com/skorasaurus/marillac/commit/87a7023bd3b499a6349be62be4e8e34401be6191) since Lou added [events support](https://github.com/mapzen/leaflet-geocoder/commit/056de87ad524bc24c0dbcb1de4c4164f5cf45fac). 

Thanks @louh for adding this! 

@royhobbstn Does this solve your use case(s)?

**Comment by louh** [comment]
You're welcome, @skorasaurus! Thanks for supplying your example. Ideally, developers will use the events to respond to selection the way they need, since we can't make too many assumptions about what's needed on the library side.

**Comment by louh** [comment]
TODO: let's include @skorasaurus's example in the documentation.

**Comment by louh** [comment]
Added 7f6c39fa699f33de1518a72476298091d7053864
