### ISSUE TITLE
Displaying point and polygon results

### ISSUE THREAD

**Issue by souperneon** [pelias/leaflet-plugin#86]
- points get a pin on the map with a tooltip (tooltip can be closed by clicking the 'x')
- polygons just zoom that map to include the polygon in the viewport with a highlighted boundary and no pin is dropped (nice to have- label for the polygon is highlighted)

**Comment by riordan** [comment]
We don't have polygon data yet but we will soon! So this is in the not too distant future.

**Comment by souperneon** [comment]
I debated adding the 'future' label on this but left it coz those issues never get looked at! 
Can't wait :)

**Comment by riordan** [comment]
Nah; we take the 'future' seriously.

**Comment by louh** [comment]
Related info for future reference and questions for debate:

When polygon geometries are available, these will be obtained by requesting from the `/place` endpoint. Thus, the handle for the `/place` response needs to also handle displaying the geometry. Currently, displaying locations are handled when a result is selected -- _before_ a place request is made. It may be likely that in the future that all location displaying happens after a `/place` request, but this introduces potentially lots of requests to be fired, particularly if, when highlighting results, it needs to auto-pan to that location.
- Do auto-pan to locations require polygon geometry?
- What if we only requested `/place` data for non-point layers?
- If all displays run through the handle for `/place`, what happens if requests are rate limited?

**Comment by louh** [comment]
This has been resolved with panning to bbox. We do not make `/place` requests automatically because of the additional traffic overhead, and ask that developers who require `/place` functionality handle this themselves by adding callbacks to event listeners.

**Comment by louh** [comment]
We should make an example that does this.

**Comment by louh** [comment]
So! `/place` does not return boundary geometry nor will it in the future. Currently it returns very little of interest, but could return more, and there is no plan from Pelias team to return geometry.

I am working on an example now which will take a selection, and uses it to make a request to WOF for the boundary geometry. Naturally this only works for WOF sources for coarse layers. We should be able to use this to indicate possibility, but since it introduces a separate dependency on another external service for very limited situations, my conclusion is that this is outside of the scope of the geocoder functionality (and perhaps would be better suited for downstream functionality bundles like mapzen.js).

**Comment by louh** [comment]
Added 1798d856209a34fde313c409f68fc373660b5a26
